const { d, numbering, P, H1, H2, H3, LI, PASO, NOTA, TABLA, PORTADA, SECCION } = require('./comun.js');
const fs = require('fs');

const doc = new d.Document({ numbering, sections: [SECCION([
  ...PORTADA('Manual del maestro', 'Cómo usar AulaFácil en el día a día', 'Versión 1.1 · Septiembre 2026'),

  H1('Antes de empezar'),
  P('AulaFácil se abre desde el navegador del celular o de la computadora. No hay nada que instalar. Si quieres tenerla como si fuera una aplicación, abre el sitio y usa la opción "Agregar a pantalla de inicio" de tu teléfono.'),
  NOTA('Si algo no se ve como esperas o acabas de recibir aviso de una versión nueva, usa el botón de la esquina superior derecha. Cuando se pone rojo y dice "Actualizar", quiere decir que hay una versión nueva esperando.'),

  H1('1. Entrar y configurar tu perfil'),
  P('Entra con tu correo y contraseña. La primera vez conviene pasar por Mi perfil, al que llegas desde tu foto en el menú lateral.'),
  H2('Lo que puedes configurar'),
  LI('Tu nombre y tu foto.'),
  LI('Tipo de maestro: de grupo (tutor o titular) o de materia.'),
  LI('Los nombres de los rubros: si en tu escuela no se dice "Exámenes" sino "Evaluaciones", aquí lo cambias y así aparecerá en las calificaciones y en el Excel.'),
  LI('Cómo calificas participación. Esta es la decisión importante y se explica en la sección 6.'),
  NOTA('El modo de participación que elijas cambia lo que ves dentro de cada grupo. Solo aparece la pestaña del modo que usas, para que no te confundas con opciones que no ocupas.'),

  H1('2. Crear un grupo y dar de alta a tus alumnos'),
  PASO('En el panel principal, presiona "Crear Nueva Clase".', 1),
  PASO('Pon el nombre del grupo, la materia y el ciclo escolar.', 1),
  PASO('Agrega a los alumnos. Tienes dos caminos.', 1),
  H2('Alumno por alumno'),
  P('Escribes nombre y matrícula. Si no quieres pensar una matrícula, el botón del dado genera una al azar, lo que evita que choque con la de otro maestro.'),
  H2('Desde un Excel'),
  P('Pegas o subes tu lista y el sistema detecta solo cuál columna es el nombre y cuál la matrícula. Es la forma rápida cuando tienes 35 alumnos.'),
  NOTA('La contraseña inicial de cada alumno es su matrícula. Diles que la cambien la primera vez que entren.'),
  H2('Las matrículas son tuyas, no del colegio'),
  P('Cada maestro lleva su propia lista de alumnos. La matrícula que tú uses solo tiene que ser única dentro de tus grupos: no importa qué número le haya puesto otro maestro al mismo estudiante, y no necesitas coordinarte con nadie ni pedir la lista oficial de control escolar.'),
  P('Eso significa que un mismo estudiante tendrá una clave distinta en cada materia. No es un defecto, es a propósito: si presta su contraseña, solo compromete esa clase, no todas.'),
  NOTA('Cuando el número que elegiste ya está ocupado en el sistema por el alumno de otro maestro, la plataforma le asigna un usuario parecido pero distinto y te lo muestra al terminar el alta. Ese usuario aparece siempre debajo del nombre en "Mis alumnos": es el que tienes que darle al alumno para entrar.'),
  P('Si tratas de reusar una matrícula que tú ya le diste a otra persona, el sistema no te deja y te dice con quién choca. Para liberarla, egresa a esa persona (sección 10).'),

  H1('3. Exámenes'),
  H2('Crear el examen'),
  PASO('Entra al grupo y presiona "Nuevo examen".', 2),
  PASO('Pon título, duración en minutos y, si quieres, hora de apertura y de cierre.', 2),
  PASO('Agrega preguntas. Hay cuatro tipos: opción múltiple, verdadero o falso, relacionar columnas y completar espacios.', 2),
  PASO('Guarda el examen y luego genera el link.', 2),
  P('Si la materia del grupo contiene la palabra "matemáticas", aparece automáticamente un teclado de símbolos (raíz, pi, división) para escribir las preguntas.'),
  H2('Repartir el examen'),
  P('Al generar el link obtienes también un código QR que puedes descargar, proyectar o imprimir. Los alumnos lo escanean con la cámara del teléfono y entran directo.'),
  H2('Durante el examen'),
  P('El examen se bloquea si el alumno se sale de la pantalla, pero no a la primera: recibe un aviso. Si vuelve a salir, entonces sí se cierra y se entrega con lo que llevaba.'),
  NOTA('Si se cae el internet no pasa nada. Las salidas causadas por una caída de red no cuentan como advertencia, las respuestas se guardan en el propio teléfono y la entrega se reintenta sola hasta lograrse. Diles a tus alumnos que no cierren la pantalla mientras diga "Entregando".'),
  H2('Ver resultados'),
  P('En la pestaña de exámenes, cada examen tiene su pantalla de resultados con la calificación de cada alumno y su estado. Puedes abrir el detalle de respuestas de cualquiera.'),
  P('Junto al nombre aparecen dos etiquetas cuando corresponde: cuántos avisos tuvo el alumno, y cuántas salidas ocurrieron sin conexión, que no contaron. Esa segunda etiqueta te sirve para juzgar si un bloqueo fue real o fue la red.'),
  P('Si alguien se bloqueó por error, el botón "Reactivar" borra el intento para que pueda volver a entrar con el mismo link, desde el principio.'),

  H1('4. Asistencia'),
  P('Eliges la fecha y marcas a cada alumno como presente, retardo, falta o falta justificada. Hay un botón para marcar a todos presentes y de ahí solo corregir las excepciones, que es más rápido cuando casi todos asistieron.'),
  NOTA('La falta justificada no es un detalle menor: si usas el modo Clase en vivo, las actividades de un día con falta justificada salen del cálculo, de modo que el alumno no queda castigado por haberse enfermado.'),

  H1('5. Tareas'),
  P('Creas la tarea con su nombre y su peso, y después la calificas. La pantalla de calificación tiene una casilla de "entregó" y un campo de calificación por alumno, y se guarda todo de una vez.'),
  P('El ícono de la tarea se elige solo según las palabras de su título.'),

  H1('6. Participación: los tres modos'),
  P('Cada maestro trabaja distinto, así que hay tres formas de calificar participación. Eliges una en tu perfil y esa es la que ves.'),

  H2('Modo Fichas'),
  P('Pensado para quien reparte fichas de colores en clase. Cada color vale puntos distintos y los valores son editables por grupo. La ficha negra funciona como multiplicador y pide capturar el valor final a mano.'),
  P('Para convertir los puntos en calificación se usa el corte: ves un ranking de mayor a menor y eliges un valor de referencia. Quien lo alcanza saca 10 y los demás se califican en proporción. El corte se guarda como una foto fija, así que agregar puntos después no cambia las calificaciones ya sacadas.'),

  H2('Modo Clase en vivo'),
  P('Pensado para quien pide participaciones durante la clase y termina contando firmas. Funciona así:'),
  PASO('Entras al grupo, pestaña "Clase en vivo", y presionas "Iniciar clase". Eliges a qué parcial pertenece.', 3),
  PASO('Aparece un código QR en tu pantalla. Los alumnos lo escanean con su cámara y quedan registrados como presentes. El código cambia solo cada 20 segundos.', 3),
  PASO('Cuando pongas un ejercicio, presiona "Nueva" y dale nombre y cuántos puntos vale.', 3),
  PASO('Los alumnos que lo hayan hecho tocan "Yo la hice" en su teléfono y van apareciendo marcados en tu lista.', 3),
  PASO('Revisas la lista, quitas a quien no participó y presionas "Cerrar actividad y dar puntos".', 3),
  PASO('Al terminar la clase, "Cerrar la clase" te da el resumen y lo guarda.', 3),
  P('Al crear cada actividad eliges cómo quieres que empiece la lista: vacía, para ir marcando a los pocos que participaron; o con todos los presentes marcados, para ir quitando a los pocos que no. Elige según cómo sea ese ejercicio y te ahorras muchos toques.'),
  NOTA('Mientras das clase no se manda nada a internet: los cambios viven en tu teléfono y se envían todos juntos al cerrar la actividad. Si en ese momento falla la red, tus marcas quedan guardadas y puedes reintentar.'),
  P('En "Clases anteriores" tienes el historial de todas las sesiones cerradas, con el detalle de quién participó en cada actividad y quién no asistió. Eso es tu respaldo si un alumno reclama después.'),

  H3('Convertir los puntos en calificación'),
  P('El botón "Ver corte" hace exactamente lo mismo que en el modo Fichas. Eliges el parcial, ves el ranking de mayor a menor y la plataforma te sugiere como referencia el puntaje más alto del grupo. Puedes cambiar ese número a mano: si el más alto juntó 40 puntos pero tú consideras que con 30 ya se merecía el 10, escribe 30 y todos los que lleguen a 30 sacan 10.'),
  P('Abajo ves en vivo la calificación que le quedaría a cada quien antes de aplicar nada. Cuando estés conforme, presionas aplicar y el corte se guarda como foto fija con su fecha y su valor de referencia. Seguir dando puntos después no altera las calificaciones ya emitidas; para tomarlos en cuenta tendrías que hacer un corte nuevo.'),

  H3('Reposiciones'),
  P('Una clase cerrada no se vuelve a abrir. Su resumen es la prueba de lo que pasó ese día y tiene que seguir diciendo la verdad. Pero sí puedes reconocerle puntos a alguien después, y eso es una reposición.'),
  P('En "Clases anteriores" abres el detalle de la clase y cada actividad tiene su botón para reponer. Eliges al alumno (solo aparecen los que no tienen puntos en esa actividad), el motivo y el porcentaje que le vas a reconocer.'),
  LI('Falta justificada: el alumno no estuvo, pero presentó justificante. Por defecto se le reconoce el 100%.'),
  LI('Entrega tardía: el alumno sí estuvo pero entregó después. Por defecto se le reconoce el 50%.'),
  P('Los dos porcentajes son editables. Los cambias para todo el grupo desde la pantalla de corte, y ahí mismo puedes moverlos caso por caso al registrar cada reposición, porque no todas las situaciones pesan igual.'),
  NOTA('La reposición no borra ni modifica el registro del día: se agrega como un renglón aparte, marcado con su motivo, su porcentaje y su fecha. En el historial ves separado quién participó en clase y quién repuso después. Los puntos sí se suman al corte, igual que las fichas.'),

  H2('Modo Formato tarea'),
  P('El más simple: una sola calificación de 0 a 10 por alumno, como si la participación fuera una tarea más. Sirve para quien evalúa participación de forma global al final del parcial.'),

  H1('7. Rubros personalizados'),
  P('Si evalúas algo que no entra en exámenes, tareas ni participación, créalo como rubro. Por ejemplo "Conducta", "Proyecto final" o "Cuaderno". Cada rubro tiene su peso y se califica de 0 a 10, igual que una tarea.'),

  H1('8. Periodos o parciales'),
  P('Defines los parciales de tu ciclo y después puedes ligar exámenes, tareas, rubros y participación a uno específico. Eso permite que las calificaciones finales se muestren parcial por parcial y no todas revueltas.'),

  H1('9. Calificaciones finales'),
  P('Aquí se junta todo. Defines la ponderación (cuánto pesa cada cosa) y el sistema calcula el promedio de cada alumno.'),
  P('Arriba hay un selector de vista: el "Resumen del ciclo" combina los parciales, y cada parcial tiene su propia vista con el desglose completo.'),
  H2('Corregir una calificación'),
  P('A veces el sistema califica mal: el examen no reconoció una respuesta que sí era válida, un bloqueo fue injusto, o simplemente sabes algo del alumno que la plataforma no puede saber. Para eso cada renglón tiene un botón de ajuste.'),
  P('Escribes la calificación final que debe llevar y el motivo. El motivo es obligatorio, y esa es la parte importante: el ajuste no borra ni reescribe el cálculo. Se guarda aparte, y la pantalla sigue mostrando cuál fue el promedio calculado por el sistema junto al que tú pusiste, marcado como ajustado.'),
  P('Si te arrepientes, "Quitar ajuste" regresa al promedio calculado sin dejar rastro en la calificación.'),
  NOTA('El Excel trae las dos columnas: "Calculado por el sistema" y el motivo del ajuste. Así, si alguien revisa las calificaciones después, puede ver qué cambiaste y por qué. Eso te protege a ti tanto como al alumno.'),
  P('El botón "Exportar a Excel" genera un archivo con una hoja por parcial más una hoja de resumen, listo para entregar en control escolar.'),
  NOTA('Todas las calificaciones se muestran en escala de 0 a 10. Internamente los exámenes y la participación se calculan en porcentaje y se convierten solo para mostrarse.'),

  H1('10. Mis alumnos: egreso y matrículas libres'),
  P('En "Mis alumnos" ves tu lista completa: todos los alumnos que tú diste de alta, aunque ya no estén en ningún grupo activo. Debajo de cada nombre aparece el usuario con el que entra y las insignias de los grupos donde está, en gris los archivados.'),
  P('AulaFácil no es el sistema de control escolar del colegio: es tu control. Cuando una generación termina, sus matrículas dejan de servirte y el colegio probablemente las va a reciclar con alumnos nuevos. Para eso existe el egreso.'),
  H2('Cómo egresar'),
  PASO('Archiva primero los grupos de esa generación. Un alumno solo se puede seleccionar si ya no está en ningún grupo activo; si no se deja marcar, la pantalla te dice exactamente por qué.', 4),
  PASO('Marca las casillas de los alumnos que se van. Puedes seleccionar a todos de una vez.', 4),
  PASO('Escribe el ciclo escolar de egreso, por ejemplo 2025-2026.', 4),
  PASO('Presiona "Egresar seleccionados" y confirma.', 4),
  NOTA('Egresar no borra nada. Sus calificaciones, asistencias, participaciones y exámenes se conservan completos, y los sigues viendo en los grupos archivados. Lo único que se libera es la matrícula y el usuario, para que puedas volver a usar ese número con un alumno nuevo.'),
  P('El enlace "Ver egresados" te muestra la lista de quienes ya salieron, con el ciclo en que lo hicieron. Es tu registro histórico: si dentro de dos años alguien pide una constancia, ahí está.'),

  H1('11. Si algo sale mal'),
  TABLA(['Situación', 'Qué hacer'], [
    ['No veo un cambio que acabo de hacer', 'Usa el botón de recargar de la esquina superior derecha'],
    ['Dice que hay versión nueva', 'Presiona "Actualizar"; la página se recarga sola'],
    ['Un alumno se bloqueó por culpa de la red', 'Revisa la etiqueta de "salidas sin red" en resultados y usa "Reactivar"'],
    ['El alumno no puede escanear el QR', 'Verifica que la clase siga abierta; el código expira a los 20 segundos'],
    ['El alumno dice que no puede reclamar', 'Debe escanear el QR primero: sin presencia registrada no hay reclamo'],
    ['No me deja reusar una matrícula', 'Ya se la diste a otra persona; egrésala desde "Mis alumnos" para liberarla'],
    ['No puedo seleccionar a un alumno para egresar', 'Sigue en un grupo activo; archiva ese grupo primero'],
    ['Un alumno faltó con justificante', 'Abre la clase en "Clases anteriores" y registra una reposición'],
    ['El examen calificó mal a un alumno', 'Usa el botón de ajuste en calificaciones finales y escribe el motivo'],
    ['La plataforma no carga después de vacaciones', 'El proyecto pudo suspenderse por inactividad; hay que reactivarlo'],
  ], [3400, 5960]),
])] });

d.Packer.toBuffer(doc).then((b) => { fs.writeFileSync('Manual-del-maestro-AulaFacil.docx', b); console.log('Manual del maestro:', b.length, 'bytes'); });
